### ISSUE TITLE
check ganglia config

### ISSUE THREAD

**Issue by rptaylor** [hep-gc/cloudinit-userdata#26]
After the changes in #18, #16, check that ganglia is working properly.
It looks like VMs are still showing up with "%f" as their name, so override_hostname may not be working correctly.

**Comment by rptaylor** [comment]
@cjdcordeiro do you know how to get the VMs registering their actual hostnames instead of the literal value "%f" ?

**Comment by cjdcordeiro** [comment]
Hi @rptaylor 

I am not aware of such gmond internal mechanism that is able to replace %f on the fly by the machine's real hostname.
The two options are:
 - pass the VMs real hostname in the YAML instead of %f
 - use the latest parameter override_hostname_bash and pass a bash instruction to tell the cloudInit modules where to get the hostname from (only available in CernVM's last release)

Cheers

**Comment by rptaylor** [comment]
Okay, thanks for the info @cjdcordeiro  !
@berghaus do you remember how the "%f" is supposed to work?
Anyway it sounds like override_hostname_bash is what we need.

**Comment by rptaylor** [comment]
Ah, so "override_hostname_bash" is not a gmond feature, but a cern-cloudinit feature.

**Comment by cjdcordeiro** [comment]
Yeah, we have implemented it for those cases where the machine's hostname is re-defined during contextualization and/or provisioning.

**Comment by rptaylor** [comment]
Like this?
    ganglia:
        globals:
            override_hostname_bash: /bin/hostname -f
I tried that , but gmond.conf ended up with
    override_hostname =

**Comment by cjdcordeiro** [comment]
Hi Ryan,

are you sure you are using CernVM 4.1.11-7.cernvm.x86_64? 
If you are, make sure that hostname -f runs well within your VM and that such command is reachable during bootime, which is when cloudinit runs.

Cheers

**Comment by rptaylor** [comment]
Hi,
It's the latest standard production release of CernVM, 3.5.1
It has cern-cloudinit-latest-5-5.2.noarch and /usr/lib/python2.6/site-packages/cloudinit/config/cc_ganglia.py appears to have the required scriptage for override_hostname_bash.
Is a different version of cern-cloudinit-latest needed?

Is it possible that the script runs at a point in the boot process before ucernvm chroots into the CVMFS OS repository?

Thanks!

**Comment by cjdcordeiro** [comment]
Hi Ryan,

well, I am not really sure when in the bootstrap does cloudInit run. We know what is the order of the cloud-init modules by looking at /etc/cloud/cloud.d*.

I believe though it should only run after ucernvm has booted since there are cloud config modules making use of OS calls and other features that wouldn't be there otherwise. 

I can have a look at your VM if you want. I'll give you my ssh key just let me know.

Cheers

**Comment by rptaylor** [comment]
Hi Cristovao,

Sure, can you send me your ssh key?

Thanks!

**Comment by cjdcordeiro** [comment]
Hi Ryan,

sorry for the late reply. Was the issue understood in the meantime? I had a look on my side and indeed the cloud init module priorities play a role in this case. 

Cheers

**Comment by rptaylor** [comment]
Hi Cristovao,

We're currently using ucernvm-prod.2.4-6 , which is more recent.

# ls -l /etc/cloud/cloud.cfg.d
total 8
-rw-r--r-- 1 root root 1674 Nov 19  2013 05_logging.cfg
-rw-r--r-- 1 root root 1520 May 11  2014 50_cernvm.cfg
-rw-r--r-- 1 root root   72 Jan  5 19:24 51_enable_ec2.cfg
-rw-r--r-- 1 root root  141 Nov 19  2013 README


50_cernvm.cfg contains 
```cloud_config_modules:
  - locale
  - set-passwords
  - timezone
  - puppet
  - chef
  - salt-minion
  - mcollective
  - disable-ec2-metadata
  - runcmd
  - cvmfs
  - condor
  - ganglia
  - shoal
```
Is that the ordering you're referring to?

I'm not sure where to look to investigate further.

**Comment by rptaylor** [comment]
Actually I was able to reproduce the issue as follows on a running VM:

```
[root@cc-west-5faaf606-8d81-48f0-b948-af8b063f173d ~]# cloud-init -d init
[root@cc-west-5faaf606-8d81-48f0-b948-af8b063f173d ~]# hostname -f
hostname: Unknown host
[root@cc-west-5faaf606-8d81-48f0-b948-af8b063f173d ~]# hostname -s
cc-west-5faaf606-8d81-48f0-b948-af8b063f173d
[root@cc-west-5faaf606-8d81-48f0-b948-af8b063f173d ~]# hostname -d
hostname: Unknown host
[root@cc-west-5faaf606-8d81-48f0-b948-af8b063f173d ~]# hostname   
cc-west-5faaf606-8d81-48f0-b948-af8b063f173d
[root@cc-west-5faaf606-8d81-48f0-b948-af8b063f173d ~]# uname -n
cc-west-5faaf606-8d81-48f0-b948-af8b063f173d
[root@cc-west-5faaf606-8d81-48f0-b948-af8b063f173d ~]# hostname -f
hostname: Unknown host
```

As described in http://unix.stackexchange.com/questions/158877/linux-hostname-f-command-is-not-working-on-rhel , 'hostname -d' does DNS lookups, whereas 'hostname' just looks up the node name (same as uname -n).  

So to work around the issue I'll just remove the '-d' argument to hostname. However there is still something funny happening with DNS after cloud-init initializes, it seems ....  Possibly related to what condor CCB puts in /etc/hosts ?

**Comment by rptaylor** [comment]
On other VMs , DNS and 'hostname -d' normally work fine, as expected.
Maybe I just screwed up this VM by re-running cloud-init while I was testing.

Anyway I believe that the networking isn't fully functional immediately after cloud-init completes. It takes a few moments. During that time 'hostname -f ' will fail but 'hostname' will work fine.

**Comment by cjdcordeiro** [comment]
Hi Ryan,

so, to my knowledge, the last changes I've applied on the Ganglia module are in CernVM from version 3.5.1.5 onwards (http://cernvm.cern.ch/portal/release_3.5.1). 
I haven't tested this version yet so I cannot really tell the module ordering in there, nevertheless that should not affect you.

I have asked Jakob Blomer to move Ganglia's contextualization to the very end, on the final modules, so that one can re-use in 'ganglia' whatever was done in 'bootcmd' and 'runcmd'. But again, this should not affect what you are doing and I am not sure it is already implemented in CernVM's last version.

What you said about the DNS makes sense. If that's the case that not really much one can do. The workaround is either ignoring -f or scheduling a job to run later when DNS is set.

btw, I usually test cloud-init by doing:
rm -fr /var/lib/cloud/instance/*
reboot

this way you get everything re-run during boot. You'll be able to distinguish either the problem is related with modules' orders, lack of environment setups or external services like DNS.

Cheers
Cris

**Comment by rptaylor** [comment]
It's working now: http://agm.cern.ch/?c=IAAS&m=load_one&r=hour&s=by%20name&hc=4&mc=2

(  @rsobie take a look at this monitoring page. )
